hash_semver: let hashtext be invoked with default collation
> ERROR: could not determine which collation to use for string hashing
> HINT:  Use the COLLATE clause to set the collation explicitly.

Hashing of a semver with a non-empty prerelease string fails as `hashtext`
requires a collation to be set. The `OidFunctionCall1(oid, arg)` macro
expands to `OidFunctionCall1Coll(oid, InvalidOid, arg)`, so put there
a default one.

TODO test case